### ISSUE TITLE
Trouble with animate.css and wow.js

### ISSUE THREAD

**Issue by SAYConnected** [IronSummitMedia/startbootstrap-grayscale#11]
Hi we have some trouble with wow integration. he doesnt work properly.
when i add some wow slideInLeft" data-wow-duration="2s" data-wow-delay="5s"
the text stay on the page and i try to change the offset but nothing append
Thanks
![screen shot 2015-03-08 at 10 58 04 am](https://cloud.githubusercontent.com/assets/7984070/6544432/12e9f918-c582-11e4-9829-274981db7a47.png)
![screen shot 2015-03-08 at 10 58 11 am](https://cloud.githubusercontent.com/assets/7984070/6544433/12eae6e8-c582-11e4-8ac3-0ab7b77e5af6.png)

and my main.js

//jQuery to collapse the navbar on scroll
$(window).scroll(function() {'use strict';
    if ($('.navbar').offset().top > 50) {
        $('.navbar-fixed-top').addClass('top-nav-collapse');
    } else {
        $('.navbar-fixed-top').removeClass('top-nav-collapse');
    }
});

//jQuery for page scrolling feature - requires jQuery Easing plugin
$(function() {'use strict';
    $('a.page-scroll').bind('click', function(event) {
        var $anchor = $(this);
        $('html, body').stop().animate({
            scrollTop: $($anchor.attr('href')).offset().top
        }, 1500, 'easeInOutExpo');
        event.preventDefault();
    });
});
// Closes the Responsive Menu on Menu Item Click
$('.navbar-collapse ul li a').click(function() {'use strict';
    $('.navbar-toggle:visible').click();
});
var wow = new WOW(
  {
    boxClass:     'wow',      // animated element css class (default is wow)
    animateClass: 'animated', // animation css class (default is animated)
    offset:       200,          // distance to the element when triggering the animation (default is 0)
    mobile:       true,       // trigger animations on mobile devices (default is true)
    live:         true,       // act on asynchronously loaded content (default is true)
    callback:     function(box) {
      // the callback is fired every time an animation is started
      // the argument that is passed in is the DOM node being animated
    }
  }
);
wow.init();

**Comment by davidtmiller** [comment]
It looks like there is a conflict happening somewhere with the WOW.js preferences. Check the jQuery again and make sure there aren't errors because it looks like some styling is messing up as well.
