### ISSUE TITLE
No textfields for grayscale

### ISSUE THREAD

**Issue by thedevthatgotaway** [IronSummitMedia/startbootstrap-grayscale#19]
When I use input type="text" it brings me the default text field and when checkingI couldn't find a custom textfield for grayscale. Does one exist that I'm missing or has a textfield not been created for this?

**Comment by davidtmiller** [comment]
No there isn't a custom text field for the theme, it might be added in the future though thanks for the suggestion!

**Comment by LuigiElleBalotta** [comment]
class="form-control" looks fine.

**Comment by davidtmiller** [comment]
@LuigiElleBalotta is right, the form-control class should work well enough. You can also customize it in some CSS if you'd like!
