### ISSUE TITLE
jquery problem

### ISSUE THREAD

**Issue by TDC-Insane** [IronSummitMedia/startbootstrap-grayscale#2]
grayscale.js (line 21)
use scrollTop: $($anchor.attr('href')).offset().top - $(".navbar").height()
instead of: $($anchor.attr('href')).offset().top

use this, so this function is more precise when the navbar is expanded
problem: how to fix the doubled active entry (/ no selected entry) in navbar when using this?

**Comment by jenyelkind** [comment]
@TDC-Insane Wow thx! ;)
