### ISSUE TITLE
Help with Less and Bootstrap Theme

### ISSUE THREAD

**Issue by KelseySteele** [IronSummitMedia/startbootstrap-grayscale#24]
Hi,

I am fairly new to web development and have never used LESS or existing Bootstrap themes before. I like the grayscale theme, but I am having trouble combining my website with your theme. 

On my homepage, I've changed the image within the intro-header class from your water and cliffs image  to an image of a soccer player on an ipad. I added this image to the grayscale.less file. I know that this less file is working, because the soccer image does appear when I view it in the browser. 

However, the image is smaller and is not styled in the same way as it should be with the grayscale theme. I've changed the image back to the theme's water image, but I have the same problem, so I know this is not because of the image size. I think this problem may be because of the CSS file that LESS is generating, but I don't know how to access this css file. The grayscale.css file remains the same even when I change the LESS file, so I'm assuming that this is not the compiled css file generated from the grayscale.less. 

I tried to host this project on gitHub with gh-branches, so that you could see it but for some reason, it still has the original image of the water and cliffs and is styled in the appropriate fashion. I am very confused. Here is the link to my github repository for this project: https://github.com/KelseySteele/vazzt-video-on-the-move-website  

Thank you!!

**Comment by CADdesign** [comment]
Did you get any help here?

**Comment by davidtmiller** [comment]
Yes, so you need to recompile the LESS file into new CSS every time you change the LESS. You can use a LESS compiler like WinLESS or Crunch if you want to do it that way, or use a build tool like Gulp or Grunt to make this happen.
