### ISSUE TITLE
Nav issue

### ISSUE THREAD

**Issue by jrean** [IronSummitMedia/startbootstrap-grayscale#9]
Hi,

Os X 10.10.2
Chrome 40.0.2214.94 (64-bit)

Load the index.html page ;
Start scrolling ;
Leave the intro section ;
Enter about section ;
Keep scrolling ;
Leave the about section ;
Enter Download section ;
...

When you enter a new section the nav menu auto-update and the section name is highlighted.
When you leave a section the nav menu auto-update and the section is not highlighted (the next/previous section is)
This is the normal behaviour.

The issue:

Load the index.html page ;
Click Download item within the nav menu ;
Scroll back to come back to About section ;
Scroll back to come back to intro section ;

When you first click on Download item within the menu, the item is highlighted and the auto-scroll brings the Download section.
When we scroll back to About section both Download and About are highlighted.
When we continue scrolling back to intro section, About item is not highlighted anymore (good) but the Download item is still highlighted (bad).

Can you help me to fix it please?

Regards and thank you for your great template!

**Comment by jrean** [comment]
Why closed?

**Comment by davidtmiller** [comment]
It should be fixed, check out the new preview file.
